[package]
name = "cat"
version = "0.1.0"
authors = ["Rémy Saissy <remy.saissy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "cat"

[dependencies]
clap = {version = "~2.33", features = ["yaml"] }
